const $ = (s, el=document) => el.querySelector(s);
const $$ = (s, el=document) => [...el.querySelectorAll(s)];
const main = $('#main'), dialog = $('#placeDialog'), dialogContent = $('#dialogContent');
const today = new Date();
let data, view = 'itinerary', map, markers = [], position = null;
const state = JSON.parse(localStorage.getItem('liberdade-state') || '{"plan":[],"favorites":[],"visited":[],"notes":{},"coords":{}}');
const save = () => localStorage.setItem('liberdade-state', JSON.stringify(state));
const mins = h => { const m=/([01]?\d|2[0-3]):([0-5]\d)/.exec(h||''); return m ? +m[1]*60 + +m[2] : null; };
const clock = m => `${String(Math.floor(m/60)).padStart(2,'0')}:${String(m%60).padStart(2,'0')}`;
const timeNow = () => today.getHours()*60+today.getMinutes();
const categoryIcon = c => ({comida:'●',café:'◆',compras:'■',mercado:'▲',cultura:'✦',atividade:'★'})[c]||'●';
const allPlaces = () => [...data.fixedEvents, ...data.places];
const getPlace = id => allPlaces().find(p=>p.id===id);
const isFixed = p => data.fixedEvents.some(x=>x.id===p.id);
const opening = p => {
  if (isFixed(p) || !p.hours) return null;
  const now=timeNow(); const pairs=[...p.hours.matchAll(/(\d{1,2}:\d{2})\s*[–-]\s*(\d{1,2}:\d{2})/g)];
  return pairs.some(x=>{const start=mins(x[1]),end=mins(x[2]);return end>=start ? now>=start&&now<=end : now>=start||now<=end;});
};
const mapUrl = p => `https://www.openstreetmap.org/search?query=${encodeURIComponent([p.name,p.address,'Liberdade, São Paulo'].filter(Boolean).join(', '))}`;
const routeUrl = p => `https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent([p.name,p.address,'São Paulo'].filter(Boolean).join(', '))}&travelmode=walking`;
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.remove('show'),2800)}
function add(id){ if(isFixed(getPlace(id))) return; if(!state.plan.includes(id)){state.plan.push(id);save();toast('Adicionado ao roteiro.')} else toast('Este local já está no roteiro.');render(); }
function toggle(arr,id){const i=state[arr].indexOf(id);i<0?state[arr].push(id):state[arr].splice(i,1);save();render();}
function move(id, dir){const i=state.plan.indexOf(id), j=i+dir;if(j<0||j>=state.plan.length)return;[state.plan[i],state.plan[j]]=[state.plan[j],state.plan[i]];save();render();}
function travel(a,b){const ca=coord(a),cb=coord(b);if(ca&&cb){const d=haversine(ca,cb);return {minutes:Math.max(2,Math.round(d/70)),label:`${Math.round(d)} m · ${Math.max(2,Math.round(d/70))} min a pé`};}return {minutes:8,label:'~8 min a pé (estimativa; localização a confirmar)'};}
function coord(p){return p.coordinates || state.coords[p.id] || null}
function haversine(a,b){const R=6371000,rad=x=>x*Math.PI/180;const dLat=rad(b.lat-a.lat),dLon=rad(b.lng-a.lng);const q=Math.sin(dLat/2)**2+Math.cos(rad(a.lat))*Math.cos(rad(b.lat))*Math.sin(dLon/2)**2;return 2*R*Math.asin(Math.sqrt(q));}
function conflicts(){let t=mins(data.day.start), issues=[];for(const id of state.plan){const p=getPlace(id);if(t+p.duration>mins(data.fixedEvents[0].start)&&t<mins(data.fixedEvents[0].end))issues.push(p.name);t+=p.duration+8;}return issues;}
function timelineItems(){const fixed=data.fixedEvents[0], before=[],after=[];let t=mins(data.day.start);for(const id of state.plan){const p=getPlace(id);const next=t+p.duration;if(next<=mins(fixed.start)) before.push({p,start:t}); else after.push({p,start:null});t=next+8;}let at=mins(fixed.end);after.forEach(x=>{x.start=at;at+=x.p.duration+8});return {before,fixed,after,end:at};}
function header(title, sub, action=''){return `<section class="view-head"><div><h2>${title}</h2><p>${sub}</p></div>${action}</section>`}
function placeCard(p, compact=false){const fav=state.favorites.includes(p.id), visit=state.visited.includes(p.id);return `<article class="place-card"><header><div><h3>${categoryIcon(p.category)} ${p.name}</h3><p class="address">${p.address||'Endereço não informado'}</p></div><button class="heart" data-favorite="${p.id}" aria-label="Favoritar ${p.name}" aria-pressed="${fav}">${fav?'♥':'♡'}</button></header><div class="meta"><span class="tag ${p.category}">${p.category}</span><span class="tag">${p.hours||'Horário não informado'}</span>${p.priority==='alta'?'<span class="priority">PRIORIDADE ALTA</span>':''}</div>${compact?'':`<p>${p.notes?.[0]||'Sem observações.'}</p>`}<div class="actions"><button class="button small secondary" data-details="${p.id}">Detalhes</button>${!isFixed(p)?`<button class="button small" data-add="${p.id}">${state.plan.includes(p.id)?'No roteiro':'Adicionar'}</button>`:''}<button class="button small ghost" data-visited="${p.id}">${visit?'✓ Visitado':'Marcar visitado'}</button></div></article>`}
function renderItinerary(){const {before,fixed,after,end}=timelineItems(),issues=conflicts(), available=mins(data.day.end)-mins(data.day.start),used=state.plan.reduce((n,id)=>n+getPlace(id).duration+8,60);const walkFor=(a,b)=>a&&b?travel(a,b):null;let html=header('Seu roteiro','11h–17h · sábado','<span class="pill">sem cadastro</span>');html+=`<section class="summary-grid"><div class="metric"><b>${state.plan.length}</b><span>paradas</span></div><div class="metric"><b>${Math.max(0,available-used)} min</b><span>livres (estimado)</span></div><div class="metric"><b>${clock(Math.min(end,mins(data.day.end)))}</b><span>término previsto</span></div><div class="metric"><b>${issues.length}</b><span>alertas</span></div></section>`;html+=`<div class="notice"><strong>Compromisso fixo.</strong> Karaokê Kampai das 14h às 15h. Ele nunca é movido pela sugestão de rota.</div>`;if(issues.length)html+=`<div class="notice"><strong>Possível conflito:</strong> ${issues.join(', ')} encosta no horário do karaokê. Reorganize ou retire uma parada.</div>`;html+='<section class="timeline">';let previous=null;const item=(x,fix=false)=>{const w=walkFor(previous,x.p);if(w)html+=`<div class="walk">↘ <b>${w.label}</b></div>`;html+=`<article class="timeline-card ${fix?'fixed':''}"><div class="time-row"><span class="time">${fix?'14:00':clock(x.start)}</span><div><h3>${x.p.name}</h3><p>${fix?'14:00–15:00 · agendamento pago':`${x.p.duration} min · ${x.p.address||'Endereço não informado'}`}</p></div>${!fix?`<div class="reorder"><button data-move="${x.p.id},-1" aria-label="Subir ${x.p.name}">↑</button><button data-move="${x.p.id},1" aria-label="Descer ${x.p.name}">↓</button></div>`:''}</div><div class="actions"><button class="button small secondary" data-details="${x.p.id}">Detalhes</button>${!fix?`<button class="button small ghost" data-remove="${x.p.id}">Remover</button>`:''}</div></article>`;previous=x.p};before.forEach(x=>item(x));item({p:fixed},true);after.forEach(x=>item(x));html+='</section>';if(!state.plan.length)html+=`<div class="empty"><b>O roteiro está livre.</b><br>Escolha uma parada em Explorar e ela aparece aqui. O karaokê já está protegido no horário certo.</div>`;html+=`<h3 class="section-title">Ações rápidas</h3><div class="actions"><button class="button secondary" id="suggest">Sugerir sequência</button><button class="button ghost" id="copyPlan">Copiar roteiro</button></div><p class="detail-note">Deslocamentos sem coordenada confirmada usam 8 minutos como estimativa editável do app. Confira antes de sair.</p>`;main.innerHTML=html;}
function renderExplore(){const categories=['todos','comida','café','compras','mercado','cultura'];const selected=main.dataset.cat||'todos', q=main.dataset.q||'', open=main.dataset.open==='1', max=+main.dataset.max||0;let items=data.places.filter(p=>(selected==='todos'||p.category===selected)&&(!q||`${p.name} ${p.address} ${p.category} ${p.notes.join(' ')}`.toLowerCase().includes(q.toLowerCase()))&&(!open||opening(p))&&(!max||p.duration<=max));let html=header('Explorar',`${items.length} locais na base`);html+=`<div class="search"><input id="query" value="${q}" placeholder="Buscar comida, café, mercado…" aria-label="Buscar locais"></div><div class="filters">${categories.map(c=>`<button class="filter ${c===selected?'active':''}" data-category="${c}">${c[0].toUpperCase()+c.slice(1)}</button>`).join('')}<button class="filter ${open?'active':''}" id="openNow">Aberto agora</button></div><div class="control-grid"><select id="duration" aria-label="Duração"><option value="0">Qualquer duração</option><option value="20" ${max===20?'selected':''}>Até 20 min</option><option value="40" ${max===40?'selected':''}>Até 40 min</option><option value="60" ${max===60?'selected':''}>Até 1 hora</option></select><button class="button secondary" id="nearMe">${position?'✓ Perto de mim':'Perto de mim'}</button></div>`;html+=items.length?`<section class="place-list">${items.map(p=>placeCard(p)).join('')}</section>`:`<div class="empty">Nada encontrado com estes filtros.<br><button class="button small secondary" id="clearFilters">Limpar filtros</button></div>`;main.innerHTML=html;}
function renderSaved(){const saved=[...state.favorites,...state.visited].filter((id,i,a)=>a.indexOf(id)===i).map(getPlace);let html=header('Salvos','Favoritos e locais visitados');html+=saved.length?`<section class="place-list">${saved.map(p=>placeCard(p)).join('')}</section>`:`<div class="empty"><b>Guarde o que chamou atenção.</b><br>Toque no coração de qualquer local para vê-lo aqui.</div>`;main.innerHTML=html;}
function renderMap(){let without=allPlaces().filter(p=>!coord(p)).length;let html=header('Mapa','Pins por categoria; coordenadas confirmadas quando disponíveis');html+=`<div class="map-key"><span><i class="dot comida"></i>comida</span><span><i class="dot café"></i>café</span><span><i class="dot compras"></i>compras</span><span><i class="dot mercado"></i>mercado</span><span><i class="dot cultura"></i>cultura</span></div><div class="map-wrap"><div id="map" class="map"></div></div><div class="map-tools"><button class="button secondary" id="geocode">Localizar endereços</button><button class="button ghost" id="locate">Usar minha localização</button></div><p class="detail-note">${without?`${without} locais ainda sem coordenada salva. “Localizar endereços” consulta OpenStreetMap somente ao tocar no botão.`:'Coordenadas salvas neste aparelho.'} Nenhum endereço ou coordenada foi inventado.</p><details class="map-list"><summary>Ver locais sem pin (${without})</summary><ul>${allPlaces().filter(p=>!coord(p)).map(p=>`<li>${p.name} — ${p.address||'endereço não informado'}</li>`).join('')}</ul></details>`;main.innerHTML=html;setTimeout(initMap);}
function initMap(){if(!window.L){$('#map').innerHTML='<div class="map-message">O mapa precisa de conexão para carregar. O restante do roteiro continua disponível.</div>';return}map=L.map('map',{zoomControl:true}).setView([-23.5584,-46.6354],15);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap'}).addTo(map);drawMarkers();}
function drawMarkers(){if(!map)return;markers.forEach(m=>m.remove());markers=[];const pins=allPlaces().filter(p=>coord(p));pins.forEach(p=>{const c=coord(p);const icon=L.divIcon({className:'',html:`<span class="tag ${p.category}" style="border:2px solid white;box-shadow:0 1px 5px #0005">${categoryIcon(p.category)}</span>`,iconSize:[26,26],iconAnchor:[13,13]});const marker=L.marker([c.lat,c.lng],{icon}).addTo(map).bindPopup(`<b>${p.name}</b><span>${p.category}</span><br><button onclick="window.open('${mapUrl(p)}','_blank')">Ver no mapa</button>`);markers.push(marker)});if(position){const u=L.circleMarker([position.lat,position.lng],{radius:9,color:'#184e9a',fillColor:'#4d91e8',fillOpacity:1}).addTo(map).bindPopup('Você está aqui');markers.push(u)}if(pins.length){const group=L.featureGroup(markers);map.fitBounds(group.getBounds().pad(.18));}}
async function geocode(){const missing=allPlaces().filter(p=>p.address&&!coord(p));if(!missing.length){toast('Todos os endereços disponíveis já foram localizados.');return}toast('Localizando endereços com OpenStreetMap…');for(const p of missing){try{const q=encodeURIComponent(`${p.address}, Liberdade, São Paulo, Brasil`);const r=await fetch(`https://nominatim.openstreetmap.org/search?format=jsonv2&limit=1&q=${q}`);const res=await r.json();if(res[0]){state.coords[p.id]={lat:+res[0].lat,lng:+res[0].lon};save();}}catch{} await new Promise(r=>setTimeout(r,1050));}renderMap();toast('Busca de endereços concluída. Confira os pins antes de sair.');}
function useLocation(){if(!navigator.geolocation){toast('Localização não é compatível neste navegador.');return}navigator.geolocation.getCurrentPosition(x=>{position={lat:x.coords.latitude,lng:x.coords.longitude};toast('Localização usada apenas nesta sessão.');render()},()=>toast('Sem localização — o app segue funcionando normalmente.'),{enableHighAccuracy:false,timeout:8000,maximumAge:300000});}
function showDetails(id){const p=getPlace(id), fav=state.favorites.includes(id), visited=state.visited.includes(id);dialogContent.innerHTML=`<button class="close" id="closeDialog" aria-label="Fechar">×</button><p class="tag ${p.category}">${p.category}</p><h2 class="detail-title">${p.name}</h2><p class="detail-address">${p.address||'Endereço não informado — edite antes de sair.'}</p><p><b>Horário:</b> ${p.hours||'Não informado'}</p><p><b>Permanência estimada:</b> ${p.duration} min <span class="detail-note">estimativa editável</span></p><ul class="detail-list">${(p.notes||[]).map(n=>`<li>${n}</li>`).join('')}</ul>${p.priority==='alta'?'<div class="notice"><strong>Prioridade alta.</strong> Agendamento já pago, das 14h às 15h.</div>':''}<div class="actions"><a class="button secondary" target="_blank" rel="noopener" href="${mapUrl(p)}">Ver no mapa</a>${p.address?`<a class="button ghost" target="_blank" rel="noopener" href="${routeUrl(p)}">Rota a pé</a>`:''}${!isFixed(p)?`<button class="button" data-add="${p.id}">${state.plan.includes(p.id)?'No roteiro':'Adicionar'}</button>`:''}<button class="heart" data-favorite="${p.id}" aria-pressed="${fav}">${fav?'♥':'♡'}</button></div><label class="field-label" for="personalNote">Nota rápida (fica neste aparelho)</label><textarea class="note-input" id="personalNote" placeholder="Ex.: pedir o choux…">${state.notes[p.id]||''}</textarea><div class="actions"><button class="button small secondary" id="saveNote" data-id="${p.id}">Salvar nota</button><button class="button small ghost" data-visited="${p.id}">${visited?'✓ Visitado':'Marcar visitado'}</button></div>`;dialog.showModal();}
function suggest(){const unfixed=state.plan.map(getPlace);if(unfixed.length<2){toast('Adicione pelo menos dois locais para sugerir uma sequência.');return}const fixedStart=mins(data.fixedEvents[0].start);let pre=[],post=[],t=mins(data.day.start);[...unfixed].sort((a,b)=>a.duration-b.duration).forEach(p=>{if(t+p.duration+8<=fixedStart){pre.push(p);t+=p.duration+8}else post.push(p)});state.plan=[...pre,...post].map(p=>p.id);save();render();toast('Sequência sugerida mantendo o karaokê fixo.');}
function copyPlan(){const {before,fixed,after}=timelineItems();const lines=[`Liberdade — ${data.day.dateLabel}`,...before.map(x=>`${clock(x.start)} · ${x.p.name}`),`14:00–15:00 · ${fixed.name} (agendado)`,...after.map(x=>`${clock(x.start)} · ${x.p.name}`)];navigator.clipboard?.writeText(lines.join('\n')).then(()=>toast('Roteiro copiado.')).catch(()=>toast(lines.join(' · ')));}
function shareDay(){const text=`Roteiro Liberdade: ${state.plan.map(id=>getPlace(id).name).join(', ')||'a definir'}. Compromisso fixo: Karaokê Kampai, 14h–15h.`;if(navigator.share)navigator.share({title:'Liberdade, vamos?',text}).catch(()=>{});else navigator.clipboard?.writeText(text).then(()=>toast('Resumo copiado para compartilhar.'));}
function bind(){const clicks=e=>{const b=e.target.closest('[data-add],[data-remove],[data-favorite],[data-visited],[data-details],[data-move],[data-category]');if(b){if(b.dataset.add)add(b.dataset.add);if(b.dataset.remove){state.plan=state.plan.filter(x=>x!==b.dataset.remove);save();render()}if(b.dataset.favorite)toggle('favorites',b.dataset.favorite);if(b.dataset.visited)toggle('visited',b.dataset.visited);if(b.dataset.details)showDetails(b.dataset.details);if(b.dataset.move){const [id,d]=b.dataset.move.split(',');move(id,+d)}if(b.dataset.category){main.dataset.cat=b.dataset.category;renderExplore()}return}if(e.target.id==='openNow'){main.dataset.open=main.dataset.open==='1'?'0':'1';renderExplore()}if(e.target.id==='clearFilters'){main.dataset.cat='todos';main.dataset.open='0';main.dataset.max='0';main.dataset.q='';renderExplore()}if(e.target.id==='nearMe')useLocation();if(e.target.id==='geocode')geocode();if(e.target.id==='locate')useLocation();if(e.target.id==='suggest')suggest();if(e.target.id==='copyPlan')copyPlan();if(e.target.id==='closeDialog')dialog.close();if(e.target.id==='saveNote'){state.notes[e.target.dataset.id]=$('#personalNote').value.trim();save();toast('Nota salva neste aparelho.')}};main.addEventListener('click',clicks);dialog.addEventListener('click',clicks);main.addEventListener('input',e=>{if(e.target.id==='query'){main.dataset.q=e.target.value;renderExplore();$('#query')?.focus();}if(e.target.id==='duration'){main.dataset.max=e.target.value;renderExplore();}});}
function render(){ $$('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===view)); if(view==='itinerary')renderItinerary();if(view==='explore')renderExplore();if(view==='saved')renderSaved();if(view==='map')renderMap(); }
$$('.bottom-nav button').forEach(b=>b.addEventListener('click',()=>{view=b.dataset.view;render()}));$('#shareDay').addEventListener('click',shareDay);bind();
fetch('./data.json').then(r=>r.json()).then(d=>{data=d;render();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});}).catch(()=>main.innerHTML='<div class="empty"><b>Não foi possível abrir a base local.</b><br>Tente novamente com conexão ou recarregue o app.</div>');
